/**
 * @openbulls/reports — template engine + i18n + markdown renderer tests.
 *
 * Coverage:
 *   - handlebars substitution (single / multi / missing vars)
 *   - i18n t() default locale + fallback on unknown locale
 *   - i18n t() with vars (handlebars-style substitution)
 *   - resolveMessage nested-key traversal + fallback
 *   - markdown renderer produces a Buffer containing title + body
 *   - renderer registry: markdown works; PDF/Excel throw TemplateMissingError
 */
import { describe, expect, it } from "vitest";

import {
  TemplateMissingError,
  asLocale,
  compileTemplate,
  createDefaultRendererResolver,
  renderMarkdown,
  renderTemplate,
  resolveMessage,
  t,
} from "../index";

describe("template engine", () => {
  it("substitutes a single var", () => {
    expect(renderTemplate("hello {{name}}", { name: "world" })).toBe("hello world");
  });

  it("renders empty for missing vars (handlebars default)", () => {
    expect(renderTemplate("x={{missing}}", {})).toBe("x=");
  });

  it("compileTemplate returns a reusable delegate", () => {
    const tpl = compileTemplate("hello {{name}}");
    expect(tpl({ name: "ada" })).toBe("hello ada");
  });
});

describe("i18n translate", () => {
  it("returns fallback when key missing", () => {
    expect(resolveMessage({}, "a.b.c", "FALLBACK")).toBe("FALLBACK");
  });

  it("returns the keyPath itself when no fallback provided", () => {
    expect(resolveMessage({}, "a.b.c")).toBe("a.b.c");
  });

  it("walks nested keys", () => {
    const catalog = { reports: { common: { footer: "Generated by Openbulls" } } };
    expect(resolveMessage(catalog, "reports.common.footer")).toBe(
      "Generated by Openbulls",
    );
  });

  it("t() defaults to tr when locale unknown", () => {
    // Should not throw; returns the keyPath when missing.
    expect(typeof t("ja", "reports.does.not.exist")).toBe("string");
  });

  it("t('en', ...) works on a known catalog key", () => {
    // We don't assert content (catalog evolves) — only that the
    // function returns a non-empty string when the path resolves.
    const out = t("en", "common.appName", {});
    expect(typeof out).toBe("string");
  });

  it("asLocale narrows unknown values to default (tr)", () => {
    expect(asLocale("fr")).toBe("tr");
    expect(asLocale("en")).toBe("en");
    expect(asLocale(undefined)).toBe("tr");
  });
});

describe("markdown renderer", () => {
  it("produces a Buffer with the title + body markers", () => {
    const buf = renderMarkdown({
      reportType: "portfolio_review",
      title: "My weekly",
      parameters: {},
      templateSource: "# {{title}}\n\nHello {{name}}\n",
      data: { name: "ada", generatedAt: "2026-07-10", locale: "en" },
    });
    const text = buf.toString("utf8");
    expect(text).toContain("My weekly");
    expect(text).toContain("Hello ada");
  });
});

describe("renderer registry", () => {
  it("returns a markdown renderer for any known type", async () => {
    const resolver = createDefaultRendererResolver();
    const out = await resolver("portfolio_review", "markdown");
    expect(out.contentType).toBe("text/markdown");
    const buf = await out.render();
    expect(buf.byteLength).toBeGreaterThan(0);
  });

  it("throws TemplateMissingError for PDF/Excel (Faz 7.3.1)", async () => {
    const resolver = createDefaultRendererResolver();
    await expect(resolver("portfolio_review", "pdf")).rejects.toBeInstanceOf(
      TemplateMissingError,
    );
    await expect(resolver("portfolio_review", "excel")).rejects.toBeInstanceOf(
      TemplateMissingError,
    );
  });
});